version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./db:/app/db
