version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn OpenSite.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - ./db:/home/app/web/db
      - static_volume:/home/app/web/staticfiles
      - ./media:/home/app/web/media
  nginx:
    build: ./nginx
    volumes:
      - ./certs/lynx-chess.com/:/etc/nginx/ssl/live/lynx-chess.com/:ro
      - static_volume:/home/app/web/staticfiles
      - ./media:/home/app/web/media
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - web

volumes:
  static_volume:
